const forbiddenWords = [
  'idiota', 'tonto', 'tonta', 'tontos', 'tontas',
  'mierda', 'mierdas', 'emierda', 'mierdera', 'mierdero',
  'imbecil', 'imbeciles', 'imbécil', 'imbéciles',
  'estupido', 'estupida', 'estupidos', 'estupidas',
  'pendejo', 'pendeja', 'pendejos', 'pendejas',
  'cabron', 'cabrona', 'cabrones', 'cabronas',
  'hijodeputa', 'hijueputa', 'hijueputas', 'hijodeputas',
  'puta', 'putas', 'puto', 'putos',
  'cojudo', 'cojuda', 'cojudos', 'cojudas',
  'boludo', 'boluda', 'boludos', 'boludas',
  'gil', 'giles', 'gilipollas',
  'capullo', 'capulla', 'capullos',
  'subnormal', 'subnormales',
  'retrasado', 'retrasada', 'retrasados',
  'tarado', 'tarada', 'tarados', 'taradas',
  'mongo', 'mongolo', 'mongolica', 'mongolico',
  'deficiente', 'deficientes',
  'anormal', 'anormales',
  'carajo', 'carajos', 'carajito',
  'conchesumadre', 'conchetumadre', 'ctm',
  'pichula', 'pichulas', 'pichulazo',
  'chucha', 'chuchas', 'chuchazo',
  'chupapico', 'chupapija', 'comepico', 'comepija',
  'verga', 'vergas', 'vergon',
  'pene', 'penes', 'cipote', 'cipotes',
  'majadero', 'majadera', 'majaderos',
  'bruto', 'bruta', 'brutos', 'brutas',
  'necio', 'necia', 'necios', 'necias',
  'ignorante', 'ignorantes',
  'analfabeto', 'analfabeta',
  'mentecato', 'mentecata',
  'zoquete', 'zoquetes',
  'burro', 'burra', 'burros', 'burras',
  'asno', 'asna', 'asnos',
  'bestia', 'bestias',
  'abombado', 'abombada',
  'zorra', 'zorras',
  'perra', 'perras',
  'prostituta', 'prostitutas',
  'ramera', 'rameras',
  'putero', 'putera',
  'culiao', 'culiada', 'culiado',
  'chinga', 'chingada', 'chingadera', 'chingar', 'chingas',
  'concha', 'panocha', 'panochas',
  'teta', 'tetas', 'tetona',
  'basura', 'basuras',
  'escoria', 'escorias',
  'desecho', 'desechos',
  'malparido', 'malparida',
  'malnacido', 'malnacida',
  'maldito', 'maldita',
  'inservible', 'inservibles',
  'inutil', 'inutiles', 'inútil', 'inútiles',
  'estorbo', 'estorbos',
  'huachafo', 'huachafa',
  'cholo', 'chola', 'cholaje',
  'indio', 'india', 'indios', 'indias',
  'longo', 'longa',
  'colla', 'collas',
  'cambita', 'cambas',
  'sureño', 'sureña',
  'matar', 'matenlo', 'matenla',
  'asesino', 'asesina', 'asesinos', 'asesinas',
  'degollar', 'apuñalar',
  'muerete', 'morite',
  'cagada', 'cagadas', 'cagadero', 'cagaste', 'cagaron', 'cague',
  'reputa',
  'kks', 'kka', 'kgar', 'kgao',
  'hueco', 'hueca', 'huecos', 'huecas',
  'animal', 'salvaje', 'salvajes',
  'demonio', 'demonios', 'diablo', 'diablos',
  'monstruo', 'monstruos',
  'mediocre', 'mediocres',
  'fracasado', 'fracasada', 'fracasados', 'fracasadas',
  'asqueroso', 'asquerosa', 'asquerosos', 'asquerosas',
  'nauseabundo', 'nauseabunda',
  'apestoso', 'apestosa',
  'cochino', 'cochina', 'cochinos', 'cochinas',
  'sucio', 'sucia', 'sucios', 'sucias',
  'puerco', 'puerca', 'puercos', 'puercas',
  'cerdo', 'cerda', 'cerdos', 'cerdas',
  'chancho', 'chancha', 'chanchos', 'chanchas',
  'lacra', 'lacras',
  'maleante', 'maleantes',
  'delincuente', 'delincuentes',
  'criminal', 'criminales',
  'ladrón', 'ladrones', 'ladrona', 'ladronas',
  'rata', 'ratas', 'ratero', 'ratera', 'rateros', 'rateras',
  'sinvergüenza', 'sinverguenza',
  'mentiroso', 'mentirosa', 'mentirosos', 'mentirosas',
  'tramposo', 'tramposa', 'tramposos', 'tramposas',
  'hipócrita', 'hipocritas', 'hipocrita',
  'cobarde', 'cobardes',
  'gallina', 'gallinas',
  'cagón', 'cagona', 'cagones', 'cagonas',
  'hdp', 'hdpm', 'ptm', 'stm', 'wtf',
  'gonorrea', 'gonorreas',
  'marica', 'maricas', 'maricón', 'maricon', 'maricones',
  'chichipato', 'chichipata',
  'güevón', 'huevon', 'güevona', 'huevona', 'huevones',
  'maluco', 'maluca',
  'pazguato', 'pazguata',
  'soplapolla', 'soplapollas',
  'mamón', 'mamona', 'mamones', 'mamon', 'mamonas',
  'lameculos', 'lameculo',
  'chismoso', 'chismosa', 'chismosos', 'chismosas',
  'metiche', 'metiches',
  'entrometido', 'entrometida',
  'envidiosa', 'envidioso', 'envidiosos', 'envidiosas',
  'amargado', 'amargada', 'amargados', 'amargadas',
  'resentido', 'resentida', 'resentidos', 'resentidas',
  'loco', 'loca', 'locos', 'locas',
  'demente', 'dementes',
  'enfermo', 'enferma', 'enfermos', 'enfermas',
  'degenerado', 'degenerada', 'degenerados', 'degeneradas',
  'pervertido', 'pervertida', 'pervertidos', 'pervertidas',
  'vicioso', 'viciosa', 'viciosos', 'viciosas',
  'drogadicto', 'drogadicta', 'drogadictos', 'drogadictas',
  'borracho', 'borracha', 'borrachos', 'borrachas',
  'alcohólico', 'alcoholico', 'alcohólicos', 'alcoholicos',
  'vago', 'vaga', 'vagos', 'vagas',
  'flojo', 'floja', 'flojos', 'flojas',
  'holgazán', 'holgazana', 'holgazanes',
  'parásito', 'parasito', 'parásitos', 'parasitos',
  'inútil', 'inutiles',
  'incompetente', 'incompetentes',
  'torpe', 'torpes',
  'lerdo', 'lerda', 'lerdos', 'lerdas',
  'miedoso', 'miedosa', 'miedosos', 'miedosas',
  'miserable', 'miserables',
  'desgraciado', 'desgraciada', 'desgraciados', 'desgraciadas',
  'desdichado', 'desdichada',
  'malnacido', 'malnacida',
  'bastardo', 'bastarda', 'bastardos', 'bastardas',
  'ilegítimo', 'ilegitimo', 'ilegítima', 'ilegitima',
  'engendro', 'engendros',
  'esperpento', 'esperpentos',
  'adefesio', 'adefesios',
  'espantajo', 'espantajos',
  'pelotudo', 'pelotuda', 'pelotudos', 'pelotudas',
  'forro', 'forra', 'forros', 'forras',
  'cretino', 'cretina', 'cretinos', 'cretinas',
  'imbancable', 'insoportable', 'insoportables',
  'detestable', 'detestables',
  'odioso', 'odiosa', 'odiosos', 'odiosas',
  'abominable', 'abominables',
  'execrable', 'execrables',
  'vil', 'viles',
  'ruin', 'ruines',
  'abyecto', 'abyecta', 'abyectos', 'abyectas',
  'infame', 'infames',
  'traidor', 'traidora', 'traidores', 'traidoras',
  'traicionero', 'traicionera',
  'falso', 'falsa', 'falsos', 'falsas',
  'farsante', 'farsantes',
  'impostor', 'impostora', 'impostores', 'impostoras',
  'charlatán', 'charlatan', 'charlatanes',
];

module.exports = forbiddenWords;