const express = require('express')
const router = express.Router()
const multer = require('multer')
const authMiddleware = require('../../middlewares/auth')
const roleMiddleware = require('../../middlewares/roleAuth')
const userController = require('../../controllers/user/userController')
const upload = multer({storage: multer.memoryStorage()})

router.get('/me', authMiddleware, userController.getMe)
router.put('/me/update', authMiddleware, userController.updateMe)
router.put('/me/photo', authMiddleware, upload.single('foto'), userController.updateMyPhoto)
router.put('/me/change-password', authMiddleware, userController.changeMyPassword)
router.get('/', authMiddleware, roleMiddleware(['ADMINISTRADOR']), userController.getAllUsers)
router.put('/:id', authMiddleware, roleMiddleware(['ADMINISTRADOR']), userController.updateUser)
router.post('/', authMiddleware, roleMiddleware(['ADMINISTRADOR']), userController.createUser)
router.delete('/:id', authMiddleware, roleMiddleware(['ADMINISTRADOR']), userController.deleteUser)
router.post('/check-email', userController.checkEmail)
router.get('/employees', authMiddleware, roleMiddleware(['SUPERVISOR', 'ADMINISTRADOR', 'REVISOR', 'APROBADOR']), userController.getEmployees)
router.get('/all', authMiddleware, roleMiddleware(['ADMINISTRADOR']), userController.getAllUsersDetailed)
router.patch('/:id/activate', authMiddleware, roleMiddleware(['ADMINISTRADOR']), userController.activateUser)
router.patch('/:id/suspend', authMiddleware, roleMiddleware(['ADMINISTRADOR']), userController.suspendUser)
router.get('/my-position', authMiddleware, userController.getMyPosition)

module.exports = router;