const express = require('express')
const router = express.Router()
const authMiddleware = require('../../middlewares/auth')
const roleMiddleware = require('../../middlewares/roleAuth')
const reviewController = require('../../controllers/approval/reviewController')

router.get('/trip-review/pending', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.getPendingTripReviews)
router.get('/trip-review/mine', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.getMyTripReviews)
router.post('/trip-review/:tripId/take', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.takeTripReview)
router.post('/trip-review/:tripId/return', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.returnTripReview)
router.get('/trip-review/:tripId', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.getTripReviewDetail)
router.post('/trip-review/:tripId/approve', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.approveTripReview)
router.post('/trip-review/:tripId/reject', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.rejectTripReview)
router.post('/trip-review/:tripId/comment', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.addTripReviewComment)
router.put('/trip-review/:tripId/comment/:commentId', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.editTripReviewComment)
router.delete('/trip-review/:tripId/comment/:commentId', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.deleteTripReviewComment)

router.get('/expense-review/pending', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.getPendingExpenseReviews)
router.get('/expense-review/mine', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.getMyExpenseReviews)
router.post('/expense-review/:tripId/take', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.takeExpenseReview)
router.post('/expense-review/:tripId/return', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.returnExpenseReview)
router.get('/expense-review/:tripId', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.getExpenseReviewDetail)
router.post('/expense-review/:tripId/approve', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.approveExpenseReview)
router.post('/expense-review/:tripId/reject', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.rejectExpenseReview)
router.post('/expense-review/:tripId/comment', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.addExpenseReviewComment)
router.put('/expense-review/:tripId/comment/:commentId', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.editExpenseReviewComment)
router.delete('/expense-review/:tripId/comment/:commentId', authMiddleware, roleMiddleware(['SUPERVISOR']), reviewController.deleteExpenseReviewComment)

module.exports = router;