const express = require('express')
const cors = require('cors')
const cookieParser = require('cookie-parser')
const app = express()

app.use(cors({
  origin: process.env.FRONTEND_URL || 'http://localhost:5173',
  credentials: true,
}))
app.use(express.json())
app.use(cookieParser())

app.get('/', (req, res) => { res.send('Hello World!') })

const PORT = process.env.PORT || 5000

const testRoute = require('./routes/test')
app.use('/test', testRoute)
const rolRoute = require('./routes/rol')
app.use('/rol', rolRoute)
const cargoRoute = require('./routes/cargo')
app.use('/cargo', cargoRoute)
const auditoriaRoute = require('./routes/auditoria')
app.use('/auditoria', auditoriaRoute)
const comentarioRoute = require('./routes/comentario')
app.use('/comentario', comentarioRoute)
const categoriaGastoRoute = require('./routes/categoriaGasto')
app.use('/categoriaGasto', categoriaGastoRoute)
const detalleFacturaRoute = require('./routes/detalle_factura')
app.use('/detalleFactura', detalleFacturaRoute)
const facturaRoute = require('./routes/factura')
app.use('/factura', facturaRoute)
const gastoRoute = require('./routes/gasto')
app.use('/gasto', gastoRoute)
const imagenRoute = require('./routes/imagen')
app.use('/imagen', imagenRoute)
const impuestoRoute = require('./routes/impuesto')
app.use('/impuesto', impuestoRoute)
const revisionRoutes = require('./routes/revision')
app.use('/revision', revisionRoutes)
const proveedorRoute = require('./routes/proveedor')
app.use('/proveedor', proveedorRoute)
const usuarioRoute = require('./routes/usuario')
app.use('/usuario', usuarioRoute)
const viajeRoute = require('./routes/viaje')
app.use('/viaje', viajeRoute)
const authRoute = require('./routes/auth')
app.use('/login', authRoute)
const adminRoutes = require('./routes/admin')
app.use('/admin', adminRoutes)
const revisorRoutes = require('./routes/revisor')
app.use('/revisor', revisorRoutes)

app.listen(PORT, () => { console.log(`Server is running on port ${PORT}`) })